package tp6_superdetodo_lab1.vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tp6_superdetodo_lab1.entidades.Producto;

public class BusquedaPrecio extends javax.swing.JInternalFrame {

    /**
     * Creates new form BusquedaNombre
     */
    public BusquedaPrecio() {
        initComponents();
        cabeceraTablaPrecio();
    
    }
    DefaultTableModel tablaPrecio = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1_listadoNombreProd = new javax.swing.JLabel();
        jLabel1_intervalo = new javax.swing.JLabel();
        jLabel2_max = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1_busquedaPrecio = new javax.swing.JTable();
        jLabel1_sugerencia = new javax.swing.JLabel();
        jButton1_VerTodosPrecios = new javax.swing.JButton();
        jTextField1_precioMin = new javax.swing.JTextField();
        jTextField1_precioMax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);

        jLabel1_listadoNombreProd.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1_listadoNombreProd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Erica\\Downloads\\lista-de-verificacion.png")); // NOI18N
        jLabel1_listadoNombreProd.setText("   Listado por precio");

        jLabel1_intervalo.setText("Ingrese el intervalo de precios: ");

        jLabel2_max.setText("máximo  $");

        jTable1_busquedaPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1_busquedaPrecio);

        jLabel1_sugerencia.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1_sugerencia.setText("Solo admite numeros y coma. Ejemplo: 3,5");

        jButton1_VerTodosPrecios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp6_superdetodo_lab1/vistas/imagenes/ver-lista.png"))); // NOI18N
        jButton1_VerTodosPrecios.setText("Ver todos");
        jButton1_VerTodosPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_VerTodosPreciosActionPerformed(evt);
            }
        });

        jTextField1_precioMin.setText("   ");
        jTextField1_precioMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_precioMinKeyReleased(evt);
            }
        });

        jTextField1_precioMax.setText("  ");
        jTextField1_precioMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_precioMaxKeyReleased(evt);
            }
        });

        jLabel1.setText("minimo $");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1_sugerencia)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1_precioMin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2_max)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1_precioMax, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1_intervalo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1_VerTodosPrecios)))
                        .addGap(48, 48, 48))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1_listadoNombreProd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_listadoNombreProd)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_intervalo)
                    .addComponent(jButton1_VerTodosPrecios))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_max)
                    .addComponent(jTextField1_precioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_precioMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1_sugerencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cabeceraTablaPrecio() {
        tablaPrecio.addColumn("Nombre");
        tablaPrecio.addColumn("Código");
        tablaPrecio.addColumn("Precio");
        tablaPrecio.addColumn("Stock");
        tablaPrecio.addColumn("Categoria");
        jTable1_busquedaPrecio.setModel(tablaPrecio);
    }

    private void borrarFilas() {
        int fila = jTable1_busquedaPrecio.getRowCount() - 1;
        //se borra de atras hacia adelante 
        for (int f = fila; f >= 0; f--) {
            tablaPrecio.removeRow(f);
        }
    }


    private void jButton1_VerTodosPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_VerTodosPreciosActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        for (Producto aux: Supermercado.listaDeProductos) {
            tablaPrecio.addRow(new Object[]{
                    aux.getDescripcion(),
                    aux.getCodigo(),
                    aux.getPrecio(),
                    aux.getStock(),
                    aux.getCategoria()
                    });
        }
    }//GEN-LAST:event_jButton1_VerTodosPreciosActionPerformed

    private void jTextField1_precioMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_precioMinKeyReleased
        // TODO add your handling code here:
        borrarFilas();
        intervaloPrecio();
    }//GEN-LAST:event_jTextField1_precioMinKeyReleased

    private void jTextField1_precioMaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_precioMaxKeyReleased
        // TODO add your handling code here:
        borrarFilas();
        intervaloPrecio();
    }//GEN-LAST:event_jTextField1_precioMaxKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_VerTodosPrecios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_intervalo;
    private javax.swing.JLabel jLabel1_listadoNombreProd;
    private javax.swing.JLabel jLabel1_sugerencia;
    private javax.swing.JLabel jLabel2_max;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable1_busquedaPrecio;
    private javax.swing.JTextField jTextField1_precioMax;
    private javax.swing.JTextField jTextField1_precioMin;
    // End of variables declaration//GEN-END:variables

    private void intervaloPrecio() {
        //double precioMin = Double.parseDouble(jLabel2_min.getText().trim());
       // double precioMax = Double.parseDouble(jLabel2_max.getText().trim());
        try {
            double precioMin =0 ;
            double precioMax =0;
            
            if (jTextField1_precioMin.getText().trim().equals("") || jTextField1_precioMax.getText().trim().equals("")) {
              precioMin = 0;
               precioMax = 0;
            }else {
                precioMin = Double.parseDouble(jTextField1_precioMin.getText().trim());
                precioMax = Double.parseDouble(jTextField1_precioMax.getText().trim());
            } 
            
            for (Producto aux : Supermercado.listaDeProductos) {
                if ( aux.getPrecio() >= precioMin &&  aux.getPrecio() <= precioMax) {
                    tablaPrecio.addRow(new Object[]{
                        aux.getDescripcion(),
                        aux.getCodigo(),
                        aux.getPrecio(),
                        aux.getStock(),
                        aux.getCategoria() 
                    });
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos para el rango de precios.");
             
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Error: " + exception.toString());
        }

    }
}
