package tp6_superdetodo_lab1.vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tp6_superdetodo_lab1.entidades.EnumCategoria;
import tp6_superdetodo_lab1.entidades.Producto;

public class BusquedaRubro extends javax.swing.JInternalFrame {

    /**
     * Creates new form BusquedaNombre
     */
    public BusquedaRubro() {
        initComponents();
        cabeceraTablaRubro();
    
    }
    DefaultTableModel tablaRubro = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1_listadoNombreProd = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1_busquedaRubros = new javax.swing.JTable();
        jLabel1_sugerencia = new javax.swing.JLabel();
        jButton1_VerTodosRubros = new javax.swing.JButton();
        jLabel1_categoria = new javax.swing.JLabel();
        jComboBox1_Rubros = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);

        jLabel1_listadoNombreProd.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1_listadoNombreProd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Erica\\Downloads\\lista-de-verificacion.png")); // NOI18N
        jLabel1_listadoNombreProd.setText("   Listado por rubro");

        jTable1_busquedaRubros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1_busquedaRubros);

        jLabel1_sugerencia.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1_sugerencia.setText("Solo admite numeros y coma. Ejemplo: 3,5");

        jButton1_VerTodosRubros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp6_superdetodo_lab1/vistas/imagenes/ver-lista.png"))); // NOI18N
        jButton1_VerTodosRubros.setText("Ver todos");
        jButton1_VerTodosRubros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_VerTodosRubrosActionPerformed(evt);
            }
        });

        jLabel1_categoria.setText("Seleccione la categoria ");

        jComboBox1_Rubros.setEditable(true);
        jComboBox1_Rubros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentos", "Limpieza", "Perfumeria" }));
        jComboBox1_Rubros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_RubrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1_sugerencia)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1_categoria)
                        .addGap(36, 36, 36)
                        .addComponent(jComboBox1_Rubros, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1_VerTodosRubros)
                        .addGap(77, 77, 77))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1_listadoNombreProd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_listadoNombreProd)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_categoria)
                    .addComponent(jComboBox1_Rubros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_VerTodosRubros))
                .addGap(18, 18, 18)
                .addComponent(jLabel1_sugerencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cabeceraTablaRubro() {
        tablaRubro.addColumn("Nombre");
        tablaRubro.addColumn("Código");
        tablaRubro.addColumn("Precio");
        tablaRubro.addColumn("Stock");
        tablaRubro.addColumn("Categoria");
        jTable1_busquedaRubros.setModel(tablaRubro);
    }

    
    private void borrarFilas() {
        int fila = jTable1_busquedaRubros.getRowCount() - 1;
        //se borra de atras hacia adelante 
        for (int f = fila; f >= 0; f--) {
            tablaRubro.removeRow(f);
        }
    }


    private void jButton1_VerTodosRubrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_VerTodosRubrosActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        for (Producto aux: Supermercado.listaDeProductos) {
            tablaRubro.addRow(new Object[]{
                    aux.getDescripcion(),
                    aux.getCodigo(),
                    aux.getPrecio(),
                    aux.getStock(),
                    aux.getCategoria()
                    });
        }
    }//GEN-LAST:event_jButton1_VerTodosRubrosActionPerformed

    private void jComboBox1_RubrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_RubrosActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        
        EnumCategoria busqCategoria  = (EnumCategoria ) jComboBox1_Rubros.getSelectedItem();
        borrarFilas();
        for (Producto aux : Supermercado.listaDeProductos) {
            if (aux.getCategoria().equals(busqCategoria)) {
                tablaRubro.addRow(new Object[]{
                    aux.getCodigo(),
                    aux.getDescripcion(), 
                    aux.getPrecio(),
                    aux.getStock()
                });
            }
    } 
    }//GEN-LAST:event_jComboBox1_RubrosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_VerTodosRubros;
    private javax.swing.JComboBox<String> jComboBox1_Rubros;
    private javax.swing.JLabel jLabel1_categoria;
    private javax.swing.JLabel jLabel1_listadoNombreProd;
    private javax.swing.JLabel jLabel1_sugerencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable1_busquedaRubros;
    // End of variables declaration//GEN-END:variables

//    private void mostrarLista() {
//        
//        
//
//    }
}
