
package tp6_superdetodo_lab1.vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tp6_superdetodo_lab1.entidades.EnumCategoria;
import tp6_superdetodo_lab1.entidades.Producto;


public class gestionProductos extends javax.swing.JInternalFrame {

    
    private Producto prodXGestionar = null;
    
    public gestionProductos() {
        initComponents();
        cabeceraTablaModelo();
    }
    DefaultTableModel tablaModelo = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1_gestionProd = new javax.swing.JLabel();
        jLabel1_cod = new javax.swing.JLabel();
        jLabel2_prod = new javax.swing.JLabel();
        jTextField1_prod = new javax.swing.JTextField();
        jTextField1_cod = new javax.swing.JTextField();
        jLabel1_precio = new javax.swing.JLabel();
        jTextField1_precio = new javax.swing.JTextField();
        jLabel1_categoria = new javax.swing.JLabel();
        jComboBox1_categoria = new javax.swing.JComboBox<>();
        jButton1_eliminarProd = new javax.swing.JButton();
        jButton2_nuevoProd = new javax.swing.JButton();
        jButton3_guardarProd = new javax.swing.JButton();
        jLabel1_stock = new javax.swing.JLabel();
        jTextField1_stock = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_tablaGralGestionProd = new javax.swing.JTable();
        jButton1_buscar = new javax.swing.JButton();
        jButton1_salir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1_gestionProd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1_gestionProd.setText("Gestión de productos");

        jLabel1_cod.setText("Código:");

        jLabel2_prod.setText("Nombre:");

        jTextField1_prod.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1_prod.setText(" ");

        jTextField1_cod.setText(" ");

        jLabel1_precio.setText("Precio:");

        jTextField1_precio.setText(" ");

        jLabel1_categoria.setText("Categoria:");

        jComboBox1_categoria.setEditable(true);
        jComboBox1_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentos", "Limpieza", "Perfumeria" }));

        jButton1_eliminarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp6_superdetodo_lab1/vistas/imagenes/circulo-de-basura (1).png"))); // NOI18N
        jButton1_eliminarProd.setText("Eliminar");
        jButton1_eliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_eliminarProdActionPerformed(evt);
            }
        });

        jButton2_nuevoProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp6_superdetodo_lab1/vistas/imagenes/agregar (3).png"))); // NOI18N
        jButton2_nuevoProd.setText("Nuevo");
        jButton2_nuevoProd.setToolTipText("");
        jButton2_nuevoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_nuevoProdActionPerformed(evt);
            }
        });

        jButton3_guardarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp6_superdetodo_lab1/vistas/imagenes/flecha-de-circulo-de-disquete-a-la-derecha.png"))); // NOI18N
        jButton3_guardarProd.setText("Guardar");
        jButton3_guardarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_guardarProdActionPerformed(evt);
            }
        });

        jLabel1_stock.setText("Stock:");

        jTextField1_stock.setText(" ");

        jTable_tablaGralGestionProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_tablaGralGestionProd);

        jButton1_buscar.setText("Buscar");
        jButton1_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_buscarActionPerformed(evt);
            }
        });

        jButton1_salir.setText("salir");
        jButton1_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2_prod)
                    .addComponent(jLabel1_cod)
                    .addComponent(jLabel1_precio)
                    .addComponent(jLabel1_stock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jTextField1_cod)
                    .addComponent(jTextField1_prod)
                    .addComponent(jTextField1_stock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1_buscar)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel1_categoria))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButton2_nuevoProd)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1_eliminarProd)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1_categoria, 0, 274, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton3_guardarProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1_salir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel1_gestionProd, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1_gestionProd)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_prod)
                    .addComponent(jTextField1_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_cod)
                    .addComponent(jTextField1_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_precio)
                    .addComponent(jTextField1_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_stock)
                    .addComponent(jTextField1_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_categoria)
                    .addComponent(jComboBox1_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2_nuevoProd)
                    .addComponent(jButton1_eliminarProd)
                    .addComponent(jButton3_guardarProd)
                    .addComponent(jButton1_salir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3_guardarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_guardarProdActionPerformed
        // TODO add your handling code here:
        try {
            int cod = Integer.parseInt(jTextField1_cod.getText());
            String nombre = jTextField1_prod.getText();
            int stock = Integer.parseInt(jTextField1_stock.getText());
            int precio = Integer.parseInt(jTextField1_precio.getText());
            EnumCategoria rubro = (EnumCategoria) jComboBox1_categoria.getSelectedItem();
            Producto prodNuevo = new Producto(nombre, cod, precio, stock, rubro);
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No debe haber campos en blanco");
                return;
            }
            boolean prod = Supermercado.listaDeProductos.add(prodNuevo);
            if (prod) {
                JOptionPane.showMessageDialog(this, "Producto agregado");
            } else {
                JOptionPane.showMessageDialog(this, "Error, código ya existente");
            }
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Error, ingresar sólo números enteros en los campos de: código, precio y stock");
        }
        
    }//GEN-LAST:event_jButton3_guardarProdActionPerformed

    private void jButton1_eliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_eliminarProdActionPerformed
        // TODO add your handling code here:
        Supermercado.listaDeProductos.remove(prodXGestionar);
        JOptionPane.showMessageDialog(this, "Producto eliminado");
        limpiarCampos();
    }//GEN-LAST:event_jButton1_eliminarProdActionPerformed

    private void jButton1_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_buscarActionPerformed
        // TODO add your handling code here:
         try {
            int cod = Integer.parseInt(jTextField1_cod.getText());
            for (Producto aux : Supermercado.listaDeProductos) {
                if (aux.getCodigo() == cod) {
                    prodXGestionar = aux;
                    JOptionPane.showMessageDialog(this, "error, reintente nuevamente");
                    break;
                } else {
                    jTextField1_prod.setText(prodXGestionar.getDescripcion());
                    jTextField1_precio.setText(prodXGestionar.getPrecio() + "");
                    jTextField1_stock.setText(prodXGestionar.getStock() + "");
                    jComboBox1_categoria.setSelectedItem(prodXGestionar.getCategoria());
                    jButton1_eliminarProd.setEnabled(true);
                }
               
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error, ingrese un valor númerico para buscar el código");
             limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error, reintente nuevamente" + e.toString());
            limpiarCampos();
        }
         
    }//GEN-LAST:event_jButton1_buscarActionPerformed

    private void jButton1_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1_salirActionPerformed

    private void jButton2_nuevoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_nuevoProdActionPerformed
        // TODO add your handling code here:
        try {
            boolean prodYaExistente= false;
            int cod = Integer.parseInt(jTextField1_cod.getText().trim());
            for (Producto aux: Supermercado.listaDeProductos) {
                if(aux.getCodigo() == cod) {
                    JOptionPane.showMessageDialog(this, "error, producto ya cargado");
                    jButton1_eliminarProd.setEnabled(true);
                } else {
                    String nombre= jTextField1_prod.getText().trim();
                    int codigo=  Integer.parseInt(jTextField1_cod.getText());
                    double precio=  Double.parseDouble(jTextField1_precio.getText());
                    int stock=  Integer.parseInt(jTextField1_stock.getText());
                    // = jComboBox1_categoria.getSelectedItem();
                    
                    Supermercado.listaDeProductos.add(new Producto(nombre, codigo, precio, stock, (EnumCategoria) jComboBox1_categoria.getSelectedItem()));
                    
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos incorrectos");
            limpiarCampos();
    }//GEN-LAST:event_jButton2_nuevoProdActionPerformed
    }
    

    private void limpiarCampos() {
        jTextField1_cod.setText("");
        jTextField1_precio.setText("");
        jTextField1_prod.setText("");
        jTextField1_stock.setText("");
        prodXGestionar = null;
        jButton1_eliminarProd.setEnabled(false);
    }
    
    
      private void cabeceraTablaModelo() {
        tablaModelo.addColumn("Nombre");
        tablaModelo.addColumn("Código");
        tablaModelo.addColumn("Precio");
        tablaModelo.addColumn("Stock");
        tablaModelo.addColumn("Categoria");
        jTable_tablaGralGestionProd.setModel(tablaModelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_buscar;
    private javax.swing.JButton jButton1_eliminarProd;
    private javax.swing.JButton jButton1_salir;
    private javax.swing.JButton jButton2_nuevoProd;
    private javax.swing.JButton jButton3_guardarProd;
    private javax.swing.JComboBox<String> jComboBox1_categoria;
    private javax.swing.JLabel jLabel1_categoria;
    private javax.swing.JLabel jLabel1_cod;
    private javax.swing.JLabel jLabel1_gestionProd;
    private javax.swing.JLabel jLabel1_precio;
    private javax.swing.JLabel jLabel1_stock;
    private javax.swing.JLabel jLabel2_prod;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_tablaGralGestionProd;
    private javax.swing.JTextField jTextField1_cod;
    private javax.swing.JTextField jTextField1_precio;
    private javax.swing.JTextField jTextField1_prod;
    private javax.swing.JTextField jTextField1_stock;
    // End of variables declaration//GEN-END:variables
}
