/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp6_superdetodo_lab1.vistas;

import tp6_superdetodo_lab1.entidades.EnumCategoria;
import tp6_superdetodo_lab1.entidades.Producto;
import java.util.TreeSet;


public class Supermercado extends javax.swing.JFrame {

    public static TreeSet<Producto> listaDeProductos =new  TreeSet<>();

    public Supermercado() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDesktopPane1_escr = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_submenuProductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_Nombre = new javax.swing.JMenuItem();
        jMenuItem_rubro = new javax.swing.JMenuItem();
        jMenuItem_precio = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1_escrLayout = new javax.swing.GroupLayout(jDesktopPane1_escr);
        jDesktopPane1_escr.setLayout(jDesktopPane1_escrLayout);
        jDesktopPane1_escrLayout.setHorizontalGroup(
            jDesktopPane1_escrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
        jDesktopPane1_escrLayout.setVerticalGroup(
            jDesktopPane1_escrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jMenu1.setText("Administración");

        jMenuItem_submenuProductos.setText("Productos");
        jMenuItem_submenuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_submenuProductosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_submenuProductos);

        jMenuBar.add(jMenu1);

        jMenu2.setText("Consultas");

        jMenuItem_Nombre.setText("Nombre");
        jMenuItem_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NombreActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Nombre);

        jMenuItem_rubro.setText("Rubro");
        jMenuItem_rubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_rubroActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_rubro);

        jMenuItem_precio.setText("Precio");
        jMenuItem_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_precioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_precio);

        jMenuBar.add(jMenu2);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1_escr)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1_escr)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NombreActionPerformed
        // TODO add your handling code here:
        jDesktopPane1_escr.removeAll();
        jDesktopPane1_escr.repaint();
        BusquedaNombre bXnombre = new BusquedaNombre();
        //por defecto la ventana esta invisible, se la agrego al escritorio y la muevo hacia el frente
        bXnombre.setVisible(rootPaneCheckingEnabled);
        jDesktopPane1_escr.add (bXnombre);
        jDesktopPane1_escr.moveToFront(bXnombre);
    }//GEN-LAST:event_jMenuItem_NombreActionPerformed

    private void jMenuItem_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_precioActionPerformed
        // TODO add your handling code here:
        jDesktopPane1_escr.removeAll();
         jDesktopPane1_escr.repaint();
         BusquedaPrecio busquedaPrecio = new BusquedaPrecio();
         busquedaPrecio.setVisible(rootPaneCheckingEnabled);
         jDesktopPane1_escr.add(busquedaPrecio);
         jDesktopPane1_escr.moveToFront(busquedaPrecio);
    }//GEN-LAST:event_jMenuItem_precioActionPerformed

    private void jMenuItem_rubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_rubroActionPerformed
        // TODO add your handling code here:
         jDesktopPane1_escr.removeAll();
         jDesktopPane1_escr.repaint();
         BusquedaPorRubroView_1 busquedaRubro = new BusquedaPorRubroView_1();
         busquedaRubro.setVisible(rootPaneCheckingEnabled);
         jDesktopPane1_escr.add(busquedaRubro);
         jDesktopPane1_escr.moveToFront(busquedaRubro);
    }//GEN-LAST:event_jMenuItem_rubroActionPerformed

    private void jMenuItem_submenuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_submenuProductosActionPerformed
        // TODO add your handling code here:
         jDesktopPane1_escr.removeAll();
         jDesktopPane1_escr.repaint();
         gestionProductos gestionProductos = new gestionProductos();
         gestionProductos.setVisible(rootPaneCheckingEnabled);
         jDesktopPane1_escr.add(gestionProductos);
         jDesktopPane1_escr.moveToFront(gestionProductos);
    }//GEN-LAST:event_jMenuItem_submenuProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supermercado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1_escr;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem_Nombre;
    private javax.swing.JMenuItem jMenuItem_precio;
    private javax.swing.JMenuItem jMenuItem_rubro;
    private javax.swing.JMenuItem jMenuItem_submenuProductos;
    // End of variables declaration//GEN-END:variables

    private void cargarProductos () {
        //
        listaDeProductos.add(new Producto ("Aceite Natural  ", 54, 597.5, 87, EnumCategoria.COMESTIBLE));
        listaDeProductos.add(new Producto ("Lustramueble Suavecito", 58, 196.6, 70, EnumCategoria.LIMPIEZA));
        listaDeProductos.add(new Producto ("Desodorante Odol", 87, 100.8, 7, EnumCategoria.PERFUMERIA));
        listaDeProductos.add(new Producto ("Desodorante para piso", 15, 180.8, 8, EnumCategoria.LIMPIEZA));
    }
    


}
